# Generated by Django 3.1.14 on 2021-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
